### ISSUE TITLE
Prefix table names to eliminate conflicts with existing databases

### ISSUE THREAD

**Issue by jtlapp** [roelandmoors/authjs-adapter-sql#10]
Boy I'm glad I found this adapter, as otherwise I might have skipped nextauth.

However, I already have a `users` table, and I'm not sure I want to be renaming my table to accommodate the adapter.

What do you think about prefixing tables names to make them unique? Or allowing us to configure prefixes?

UPDATE: I could look into merging the tables, but I'm afraid that could create all sorts of unexpected problems. For maximum reliability, it seems like each component should manage its tables separately.

**Comment by roelandmoors** [comment]
yes, configuration sounds like a good idea.

**Comment by jtlapp** [comment]
Check out how the [supabase adapter](https://authjs.dev/reference/adapter/supabase) suggests doing things. All of its tables have the prefix `next_auth.`, and it suggests synchronizing `next_auth.users` with the app's `users` table as follows:

```sql
create table users (
  -- UUID from next_auth.users
  id uuid not null primary key,
  name text,
  email text,
  image text,
  constraint "users_id_fkey" foreign key ("id")
        references  next_auth.users (id) match simple
        on update no action
        on delete cascade -- if user is deleted in NextAuth they will also be deleted in our public table.
);
alter table users enable row level security;
create policy "Can view own user data." on users for select using (next_auth.uid() = id);
create policy "Can update own user data." on users for update using (next_auth.uid() = id);

// This trigger automatically creates a user entry when a new user signs up via NextAuth.
create function public.handle_new_user()
returns trigger as $$
begin
  insert into public.users (id, name, email, image)
  values (new.id, new.name, new.email, new.image);
  return new;
end;
$$ language plpgsql security definer;
create trigger on_auth_user_created
  after insert on next_auth.users
  for each row execute procedure public.handle_new_user();
```

**Comment by jtlapp** [comment]
Actually, the supabase prefix `next_auth.` is a schema rather than a name prefix. Maybe that's another solution?

**Comment by jtlapp** [comment]
Here's the supabase adapter SQL. It looks like the solution is to [prefix the table names with the schema](https://github.com/nextauthjs/next-auth/blob/main/packages/adapter-supabase/supabase/migrations/20221108043803_create_next_auth_schema.sql), anyway. (I don't have any experience working with multiple schemas.)

```sql
CREATE SCHEMA next_auth;

GRANT USAGE ON SCHEMA next_auth TO service_role;
GRANT ALL ON SCHEMA next_auth TO postgres;

--
-- Create users table
--
CREATE TABLE IF NOT EXISTS next_auth.users
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    name text,
    email text,
    "emailVerified" timestamp with time zone,
    image text,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT email_unique UNIQUE (email)
);

GRANT ALL ON TABLE next_auth.users TO postgres;
GRANT ALL ON TABLE next_auth.users TO service_role;
```

**Comment by roelandmoors** [comment]
Yes, you can use triggers to keep other user tables in sync. 
Or maybe use an auth/provider callback?

Does your current user table has a very different structure?
I would prefer a single user table in a project if possible, but I don't now how different your table structure is.
Would more configuration settings make this possible for you? 

Schema is only for postgres, not mysql. I was thinking of creating a `prefix` setting that can be used for both.
Examples: `auth.` (postgresql schema) or `auth_` (table name prefix) of even something like `auth.next-`

**Comment by roelandmoors** [comment]
I added the prefix option: https://github.com/roelandmoors/authjs-adapter-sql#configuration

**Comment by jtlapp** [comment]
That's awesome! Thanks so much!

As for your question, I'm mainly worried about two independently maintained software components trying to manage the same table. I think it's safest to use triggers to sync the tables.

Feel free to close this, unless you have reason to keep it open.
