### ISSUE TITLE
Issue with named imports in Vite/Sveltekit (CJS vs ESM)

### ISSUE THREAD

**Issue by Sdocquir** [roelandmoors/authjs-adapter-sql#16]
Running into an odd issue that's caused by how vite and sveltekit build packages differently for server or clients.

Here's an example : https://github.com/sveltejs/kit/issues/5607

Seems like the most basic solution would be to use named exports (along with default), for the main `SqlAdapter` and any `buildXXX` functions in the driver folder.

**Comment by roelandmoors** [comment]
Maybe you could try something like this?
https://github.com/FirebaseExtended/rxfire/issues/52#issuecomment-1359358011

If it works, I'm happy to add it to the source if current code keeps working. 

Or if you have a simple repo I could test?

**Comment by Sdocquir** [comment]
I couldn't get that solution working at first glance, but I'm also not an expert on CJS/ESM and package imports.

**Comment by roelandmoors** [comment]
I added named exports in v0.2.4.
Could you check if it works now?
